// General Definition
`define WRITE_EN_BUS_WIDTH              512
`define AC_DAC_WIDTH                    6
//
// Address Definition
//
`define AC_VPORT_CALIB0_ADDR                 32
`define AC_VPORT_CALIB1_ADDR                 33
`define VMAIN_ADDR                           34
`define VTEMP0_ADDR                          35
`define VTEMP1_ADDR                          36
`define VTEMP2_ADDR                          37
`define VTEMP3_ADDR                          38
`define ICHANNEL0_ADDR                       39
`define ICHANNEL1_ADDR                       40
`define ICHANNEL2_ADDR                       41
`define ICHANNEL3_ADDR                       42
`define ICHANNEL4_ADDR                       43
`define ICHANNEL5_ADDR                       44
`define ICHANNEL6_ADDR                       45
`define ICHANNEL7_ADDR                       46
`define ICHANNEL8_ADDR                       47
`define ICHANNEL9_ADDR                       48
`define ICHANNEL10_ADDR                      49
`define ICHANNEL11_ADDR                      50
`define AC_VPORT0_ADDR                       51
`define AC_VPORT1_ADDR                       52
`define AC_VPORT2_ADDR                       53
`define AC_VPORT3_ADDR                       54
`define AC_VPORT4_ADDR                       55
`define AC_VPORT5_ADDR                       56
`define AC_VPORT5_ADDR                       57
`define AC_VPORT6_ADDR                       58
`define AC_VPORT7_ADDR                       59
`define AC_VPORT8_ADDR                       60
`define AC_VPORT9_ADDR                       61
`define AC_VPORT10_ADDR                      62
`define AC_VPORT11_ADDR                      63
`define VPORT_ADDR                           64
`define SYS_STATUS_ADDR                      128
`define AC_VPORT_CALIB_MAX_ADDR              129
`define AC_VPORT_CALIB_MIN_ADDR              130
`define VMAIN_TH_LOW_ADDR                    131
`define VMAIN_TH_HIGH_ADDR                   132
`define VMAIN_RPS_TH_ADDR                    133
`define TMR_VMAIN_CNT_ADDR                   134
`define TMR_VMAIN_RPS_CNT_ADDR               135
`define TMR_OVLD_ADDR                        196
`define TMR_AC_DISCO_ADDR                    197
`define TMR_MPS_ADDR                         198
`define TMR_DC_DISCO_ADDR                    199
`define TMR_RCV_OVLD_ADDR                    200
`define TMR_RCV_DISCO_ADDR                   201
`define TMR_VMAIN_ADDR                       202
`define TMR_VMAIN_RPS_ADDR                   203
`define PORT0_STATUS1_ADDR                   257
`define PORT1_STATUS1_ADDR                   258
`define PORT2_STATUS1_ADDR                   259
`define PORT3_STATUS1_ADDR                   260
`define PORT4_STATUS1_ADDR                   261
`define PORT5_STATUS1_ADDR                   262
`define PORT6_STATUS1_ADDR                   263
`define PORT7_STATUS1_ADDR                   264
`define PORT8_STATUS1_ADDR                   265
`define PORT9_STATUS1_ADDR                   266
`define PORT10_STATUS1_ADDR                  267
`define PORT11_STATUS1_ADDR                  268
`define PORT0_STATUS2_ADDR                   269
`define PORT1_STATUS2_ADDR                   270
`define PORT2_STATUS2_ADDR                   271
`define PORT3_STATUS2_ADDR                   272
`define PORT4_STATUS2_ADDR                   273
`define PORT5_STATUS2_ADDR                   274
`define PORT6_STATUS2_ADDR                   275
`define PORT7_STATUS2_ADDR                   276
`define PORT8_STATUS2_ADDR                   277
`define PORT9_STATUS2_ADDR                   278
`define PORT10_STATUS2_ADDR                  279
`define PORT11_STATUS2_ADDR                  280
`define ICUT0_ADDR                           281
`define ICUT1_ADDR                           282
`define ICUT2_ADDR                           283
`define ICUT3_ADDR                           284
`define ICUT4_ADDR                           285
`define ICUT5_ADDR                           286
`define ICUT6_ADDR                           287
`define ICUT7_ADDR                           288
`define ICUT8_ADDR                           289
`define ICUT9_ADDR                           290
`define ICUT10_ADDR                          291
`define ICUT11_ADDR                          292
`define TMR_OVLD_CNT0_ADDR                   293
`define TMR_OVLD_CNT1_ADDR                   294
`define TMR_OVLD_CNT2_ADDR                   295
`define TMR_OVLD_CNT3_ADDR                   296
`define TMR_OVLD_CNT4_ADDR                   297
`define TMR_OVLD_CNT5_ADDR                   298
`define TMR_OVLD_CNT6_ADDR                   299
`define TMR_OVLD_CNT7_ADDR                   300
`define TMR_OVLD_CNT8_ADDR                   301
`define TMR_OVLD_CNT9_ADDR                   302
`define TMR_OVLD_CNT10_ADDR                  303
`define TMR_OVLD_CNT11_ADDR                  304
`define AC_VPORT_CALIB_MAX_ADDR              305
`define AC_VPORT0_MAX_ADDR                   306
`define AC_VPORT1_MAX_ADDR                   307
`define AC_VPORT2_MAX_ADDR                   308
`define AC_VPORT3_MAX_ADDR                   309
`define AC_VPORT4_MAX_ADDR                   310
`define AC_VPORT5_MAX_ADDR                   311
`define AC_VPORT6_MAX_ADDR                   312
`define AC_VPORT7_MAX_ADDR                   313
`define AC_VPORT8_MAX_ADDR                   314
`define AC_VPORT9_MAX_ADDR                   315
`define AC_VPORT10_MAX_ADDR                  316
`define AC_VPORT11_MAX_ADDR                  317
`define AC_VPORT_CALIB_MIN_ADDR              318
`define AC_VPORT0_MIN_ADDR                   319
`define AC_VPORT1_MIN_ADDR                   320
`define AC_VPORT2_MIN_ADDR                   321
`define AC_VPORT3_MIN_ADDR                   322
`define AC_VPORT4_MIN_ADDR                   323
`define AC_VPORT5_MIN_ADDR                   324
`define AC_VPORT6_MIN_ADDR                   325
`define AC_VPORT7_MIN_ADDR                   326
`define AC_VPORT8_MIN_ADDR                   327
`define AC_VPORT9_MIN_ADDR                   328
`define AC_VPORT10_MIN_ADDR                  329
`define AC_VPORT11_MIN_ADDR                  330
`define AC_AMP_CALIB_ADDR                    331
`define AC_AMP0_ADDR                         332
`define AC_AMP1_ADDR                         333
`define AC_AMP2_ADDR                         334
`define AC_AMP3_ADDR                         335
`define AC_AMP4_ADDR                         336
`define AC_AMP5_ADDR                         337
`define AC_AMP6_ADDR                         338
`define AC_AMP7_ADDR                         339
`define AC_AMP8_ADDR                         340
`define AC_AMP9_ADDR                         341
`define AC_AMP10_ADDR                        342
`define AC_AMP11_ADDR                        343
`define TMR_AC_DISCO_CNT0_ADDR               344
`define TMR_AC_DISCO_CNT1_ADDR               345
`define TMR_AC_DISCO_CNT2_ADDR               346
`define TMR_AC_DISCO_CNT3_ADDR               347
`define TMR_AC_DISCO_CNT4_ADDR               348
`define TMR_AC_DISCO_CNT5_ADDR               349
`define TMR_AC_DISCO_CNT6_ADDR               350
`define TMR_AC_DISCO_CNT7_ADDR               351
`define TMR_AC_DISCO_CNT8_ADDR               352
`define TMR_AC_DISCO_CNT9_ADDR               353
`define TMR_AC_DISCO_CNT10_ADDR              354
`define TMR_AC_DISCO_CNT11_ADDR              355
`define TMR_MPS_CNT0_ADDR                    356
`define TMR_MPS_CNT1_ADDR                    357
`define TMR_MPS_CNT2_ADDR                    358
`define TMR_MPS_CNT3_ADDR                    359
`define TMR_MPS_CNT4_ADDR                    360
`define TMR_MPS_CNT5_ADDR                    361
`define TMR_MPS_CNT6_ADDR                    362
`define TMR_MPS_CNT7_ADDR                    363
`define TMR_MPS_CNT8_ADDR                    364
`define TMR_MPS_CNT9_ADDR                    365
`define TMR_MPS_CNT10_ADDR                   366
`define TMR_MPS_CNT11_ADDR                   367
`define TMR_DC_DISCO_CNT0_ADDR               368
`define TMR_DC_DISCO_CNT1_ADDR               369
`define TMR_DC_DISCO_CNT2_ADDR               370
`define TMR_DC_DISCO_CNT3_ADDR               371
`define TMR_DC_DISCO_CNT4_ADDR               372
`define TMR_DC_DISCO_CNT5_ADDR               373
`define TMR_DC_DISCO_CNT6_ADDR               374
`define TMR_DC_DISCO_CNT7_ADDR               375
`define TMR_DC_DISCO_CNT8_ADDR               376
`define TMR_DC_DISCO_CNT9_ADDR               377
`define TMR_DC_DISCO_CNT10_ADDR              378
`define TMR_DC_DISCO_CNT11_ADDR              379
`define TMR_RCV_DISCO_CNT0_ADDR              380
`define TMR_RCV_DISCO_CNT1_ADDR              381
`define TMR_RCV_DISCO_CNT2_ADDR              382
`define TMR_RCV_DISCO_CNT3_ADDR              383
`define TMR_RCV_DISCO_CNT4_ADDR              384
`define TMR_RCV_DISCO_CNT5_ADDR              385
`define TMR_RCV_DISCO_CNT6_ADDR              386
`define TMR_RCV_DISCO_CNT7_ADDR              387
`define TMR_RCV_DISCO_CNT8_ADDR              388
`define TMR_RCV_DISCO_CNT9_ADDR              389
`define TMR_RCV_DISCO_CNT10_ADDR             390
`define TMR_RCV_DISCO_CNT11_ADDR             391
`define TMR_RCV_OVLD_CNT0_ADDR               392
`define TMR_RCV_OVLD_CNT1_ADDR               393
`define TMR_RCV_OVLD_CNT2_ADDR               394
`define TMR_RCV_OVLD_CNT3_ADDR               395
`define TMR_RCV_OVLD_CNT4_ADDR               396
`define TMR_RCV_OVLD_CNT5_ADDR               397
`define TMR_RCV_OVLD_CNT6_ADDR               398
`define TMR_RCV_OVLD_CNT7_ADDR               399
`define TMR_RCV_OVLD_CNT8_ADDR               400
`define TMR_RCV_OVLD_CNT9_ADDR               401
`define TMR_RCV_OVLD_CNT10_ADDR              402
`define TMR_RCV_OVLD_CNT11_ADDR              403
`define PORT_OFF_DA_ADDR                     2001
`define APP_OUT0_ADDR                        2032
`define APP_OUT1_ADDR                        2033
`define APP_OUT2_ADDR                        2034
`define APP_OUT3_ADDR                        2035
`define APP_OUT4_ADDR                        2036
`define APP_OUT5_ADDR                        2037
`define APP_OUT6_ADDR                        2038
`define APP_OUT7_ADDR                        2039
`define ADC_BUF0_DEFAULT                     16'h0000
`define ADC_BUF1_DEFAULT                     16'h0000
`define ADC_BUF2_DEFAULT                     16'h0000
`define ADC_BUF3_DEFAULT                     16'h0000
`define ADC_BUF4_DEFAULT                     16'h0000
`define ADC_BUF5_DEFAULT                     16'h0000
`define ADC_BUF6_DEFAULT                     16'h0000
`define ADC_BUF7_DEFAULT                     16'h0000
`define ADC_BUF8_DEFAULT                     16'h0000
`define ADC_BUF9_DEFAULT                     16'h0000
`define ADC_BUF10_DEFAULT                    16'h0000
`define ADC_BUF11_DEFAULT                    16'h0000
`define ADC_BUF12_DEFAULT                    16'h0000
`define ADC_BUF13_DEFAULT                    16'h0000
`define ADC_BUF14_DEFAULT                    16'h0000
`define ADC_BUF15_DEFAULT                    16'h0000
`define ADC_BUF16_DEFAULT                    16'h0000
`define ADC_BUF17_DEFAULT                    16'h0000
`define ADC_BUF18_DEFAULT                    16'h0000
`define ADC_BUF19_DEFAULT                    16'h0000
`define ADC_BUF20_DEFAULT                    16'h0000
`define ADC_BUF21_DEFAULT                    16'h0000
`define ADC_BUF22_DEFAULT                    16'h0000
`define ADC_BUF23_DEFAULT                    16'h0000
`define ADC_BUF24_DEFAULT                    16'h0000
`define ADC_BUF25_DEFAULT                    16'h0000
`define ADC_BUF26_DEFAULT                    16'h0000
`define ADC_BUF27_DEFAULT                    16'h0000
`define ADC_BUF28_DEFAULT                    16'h0000
`define ADC_BUF29_DEFAULT                    16'h0000
`define ADC_BUF30_DEFAULT                    16'h0000
`define ADC_BUF31_DEFAULT                    16'h0000
`define ADC_BUF32_DEFAULT                    16'h0000
`define SYS_STATUS_DEFAULT                   16'h0000
`define AC_VPORT_CALIB_MAX_DEFAULT           16'h0000
`define AC_VPORT_CALIB_MIN_DEFAULT           16'h0000
`define VMAIN_TH_LOW_DEFAULT                 16'h02e5
`define VMAIN_TH_HIGH_DEFAULT                16'h03e7
`define VMAIN_RPS_TH_DEFAULT                 16'h0318
`define TMR_VMAIN_CNT_DEFAULT                16'h0000
`define TMR_VMAIN_RPS_CNT_DEFAULT            16'h0000
`define TMR_OVLD_DEFAULT                     16'h0260
`define TMR_AC_DISCO_DEFAULT                 16'h0007
`define TMR_MPS_DEFAULT                      16'h001d
`define TMR_DC_DISCO_DEFAULT                 16'h00ab
`define TMR_RCV_OVLD_DEFAULT                 16'h0989
`define TMR_RCV_DISCO_DEFAULT                16'h01e8
`define TMR_VMAIN_DEFAULT                    16'h000f
`define TMR_VMAIN_RPS_DEFAULT                16'h000f
`define ICUT0_DEFAULT                        16'h0099
`define ICUT1_DEFAULT                        16'h0099
`define ICUT2_DEFAULT                        16'h0099
`define ICUT3_DEFAULT                        16'h0099
`define ICUT4_DEFAULT                        16'h0099
`define ICUT5_DEFAULT                        16'h0099
`define ICUT6_DEFAULT                        16'h0099
`define ICUT7_DEFAULT                        16'h0099
`define ICUT8_DEFAULT                        16'h0099
`define ICUT9_DEFAULT                        16'h0099
`define ICUT10_DEFAULT                       16'h0099
`define ICUT11_DEFAULT                       16'h0099
`define APP_OUT0_DEFAULT                     16'h0FFF
`define APP_OUT1_DEFAULT                     16'h0000
`define APP_OUT2_DEFAULT                     16'h0000
`define APP_OUT3_DEFAULT                     16'h0000
`define APP_OUT4_DEFAULT                     16'h0000
`define APP_OUT5_DEFAULT                     16'h0000
`define APP_OUT6_DEFAULT                     16'h0000
`define APP_OUT7_DEFAULT                     16'h0000
