 // OCP include file

//`define OCP_BASE_ADDR				12'h600
//
//`define OCP_TIMER_CFG_ADDR		`OCP_BASE_ADDR + 12'h000
//`define OCP_DBG_CTRL_LSB_ADDR		`OCP_BASE_ADDR + 12'h002
//`define OCP_DBG_CTRL_MSB_ADDR		`OCP_BASE_ADDR + 12'h003
//`define OCP_BKPT_CFG_ADDR			`OCP_BASE_ADDR + 12'h004
//`define OCP_IRQ_CFG_ADDR			`OCP_BASE_ADDR + 12'h008
//`define OCP_IRQ_STAT_ADDR			`OCP_BASE_ADDR + 12'h00A
//`define OCP_MCU_STAT_1_ADDR		`OCP_BASE_ADDR + 12'h00C
//`define OCP_MCU_STAT_2_ADDR		`OCP_BASE_ADDR + 12'h00E
//`define OCP_MCU_STAT_3_ADDR		`OCP_BASE_ADDR + 12'h010
//`define OCP_MCU_STAT_4_ADDR		`OCP_BASE_ADDR + 12'h012
//`define OCP_MCU_STAT_5_ADDR		`OCP_BASE_ADDR + 12'h014
//`define OCP_IO_CTRL_ADDR			`OCP_BASE_ADDR + 12'h016

//`define OCP_IROM_BASE_ADDR		12'h800
//`define OCP_IRAM_BASE_ADDR		12'h800


`define OCP_BASE_ADDR				1536

`define OCP_TIMER_CFG_ADDR			`OCP_BASE_ADDR+0
`define OCP_DBG_CTRL_LSB_ADDR		`OCP_BASE_ADDR+2
`define OCP_DBG_CTRL_MSB_ADDR		`OCP_BASE_ADDR+3
`define OCP_BKPT_CFG_ADDR			`OCP_BASE_ADDR+4
`define OCP_IRQ_CFG_ADDR			`OCP_BASE_ADDR+8
`define OCP_IRQ_STAT_ADDR			`OCP_BASE_ADDR+10
`define OCP_MCU_STAT_1_ADDR			`OCP_BASE_ADDR+12
`define OCP_MCU_STAT_2_ADDR			`OCP_BASE_ADDR+14
`define OCP_MCU_STAT_3_ADDR			`OCP_BASE_ADDR+16
`define OCP_MCU_STAT_4_ADDR			`OCP_BASE_ADDR+18
`define OCP_MCU_STAT_5_ADDR			`OCP_BASE_ADDR+20
`define OCP_IO_CTRL_ADDR			`OCP_BASE_ADDR+22

`define OCP_IROM_BASE_ADDR			2048
`define OCP_IRAM_BASE_ADDR			2048


// DBG_CTRL_MSB bits
`define OCP_DBG_CTRL_OCM_IMEM_SEL_BIT		0
`define OCP_DBG_CTRL_IMEM_CS_OVR_EN_BIT		1
`define OCP_DBG_CTRL_IMEM_CS_OVR_VAL_BIT	2
`define OCP_DBG_CTRL_EXT_IRQ_SEL_BITS		5:3
`define OCP_DBG_CTRL_MEM_CLK_GATE_EN_BIT	6
`define OCP_DBG_CTRL_MCU_CLK_GATE_EN_BIT	7
`define OCP_DBG_CTRL_REGS_CLK_GATE_EN_BIT	8



// OCP_STAT bits
`define OCP_STAT_AL_BIT		0
`define OCP_STAT_NACK_BIT	1
`define OCP_STAT_ARDY_BIT	2
`define OCP_STAT_RRDY_BIT	3
`define OCP_STAT_XRDY_BIT	4
`define OCP_STAT_GC_BIT		5
`define OCP_STAT_STC_BIT	6
`define OCP_STAT_AERR_BIT	7
`define OCP_STAT_BF_BIT		8
`define OCP_STAT_AAS_BIT	9
`define OCP_STAT_XUDF_BIT	10
`define OCP_STAT_ROVR_BIT	11
`define OCP_STAT_BB_BIT		12
`define OCP_STAT_RDR_BIT	13
`define OCP_STAT_XDR_BIT	14
